---
deployment:
 tasks:
 - export DEPLOYPATH=/home2/eigsixz6/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp community_map.html $DEPLOYPATH
 - /bin/cp pet_guidelines.html $DEPLOYPATH
 - /bin/cp events.html $DEPLOYPATH
 - /bin/cp interior_photos.html $DEPLOYPATH
 - /bin/cp exterior_photos.html $DEPLOYPATH
 - /bin/cp style2.css $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
